# Generated by Django 4.2.9 on 2024-01-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_debut',
            field=models.DateTimeField(),
        ),
    ]
